# Generated by Django 5.1.4 on 2025-01-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='gender',
            field=models.CharField(default='unisex', max_length=50, verbose_name='Мужское/женское'),
        ),
    ]
