# Generated by Django 5.1.4 on 2025-01-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_shopitem_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='gender',
            field=models.CharField(default='unisex', help_text="указывать либо 'men', либо 'women', с маленькой буквы", max_length=50, verbose_name='Мужское/женское'),
        ),
        migrations.CreateModel(
            name='SliderForItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='items_slides/%Y/%m/%d/', verbose_name='Изображения для слайдера')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_for_item', to='home.shopitem', verbose_name='Товар')),
            ],
        ),
    ]
