# Generated by Django 5.1.4 on 2025-01-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_shopitem_gender_sliderforitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderforitem',
            options={'verbose_name': 'Фото для слайдера', 'verbose_name_plural': 'Фото для слайдеров'},
        ),
    ]
